language: java

sudo: false

cache:
  directories:
  - $HOME/.mx/cache

before_install:
- unset GEM_PATH GEM_HOME IRBRC

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test specs :command_line'
  - env: JT='test specs :language :security'
  - env: JT='test specs :core_a'
  - env: JT='test specs :core_b'
  - env: JT='test specs :library'
  - env: JT='test specs :truffle'
  - env: JT='test integration'
  - env: JT='test gems'
  - env: JT='test tck'
  - env: JT='lint' COMMAND='rvm install 2.1.0' SKIP_BUILD=true V=1
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- echo MX_BINARY_SUITES=truffle,sdk >> mx.truffleruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.truffleruby/env
- if [ -z "$SKIP_BUILD" ]; then tool/jt.rb build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - master
    - /^try/
